baseURL = 'https://homelab.mad9scientist.com/'
languageCode = 'en-US'
title = "Mad9Scientist's HomeLab 🧪"
theme = 'ananke'

enableRobotsTXT = true


[params.ananke.social.follow]
networks = [
  "github",
  "twitter",
  "bluesky",
]

[params.ananke.social.share]
networks = [
  "bluesky",
  "twitter",
]

[params.ananke.social.github]
username = "mad9scientist"
profilelink = "https://github.com/mad9scientist/homelabsite"
rel = "me"

[params.ananke.social.twitter]
username = "mad9scientist"
profilelink = "https://twitter.com/mad9scientist"
rel = "me"

[params.ananke.social.bluesky]
username = "mad9scientist.bsky.social"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Mad9Scientist"
  favicon = "https://mad9scientist.com/m9s/wp-content/themes/mad9scientist-2g/img/favicon.ico"
  site_logo = ""
  description = "Mad9Scientist Homelab Adventures..."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  recent_posts_number = 6
  show_reading_time = true
  custom_css = ["custom.css"]

# Allow HTML
[markup.goldmark.renderer]
unsafe=true

[menus]
[[menus.main]]
  name = 'Articles'
  pageRef = '/post/'
  weight = 5
[[menus.main]]
  name = 'Hardware'
  pageRef = '/hardware'
  weight = 10
[[menus.main]]
  name = 'Software'
  pageRef = '/software'
  weight = 15
[[menus.main]]
  name = 'Services'
  pageRef = '/services'
  weight = 20
[[menus.main]]
  name = 'Mad9Scientist.com'
  url = 'https://mad9scientist.com'
  weight = 25
